// Code generated by entc, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/ftomza/go-qcbalu/wallet/repository/ent/schema"
	"github.com/ftomza/go-qcbalu/wallet/repository/ent/wallet"

	"github.com/facebook/ent"
)

// The init function reads all schema descriptors with runtime
// code (default values, validators or hooks) and stitches it
// to their package variables.
func init() {
	walletMixin := schema.Wallet{}.Mixin()
	walletMixinHooks2 := walletMixin[2].(interface{ Hooks() []ent.Hook }).Hooks()
	wallet.Hooks[0] = walletMixinHooks2[0]
	walletMixinFields1 := walletMixin[1].Fields()
	walletMixinFields2 := walletMixin[2].Fields()
	walletFields := schema.Wallet{}.Fields()
	_ = walletFields
	// walletDescCreateTime is the schema descriptor for create_time field.
	walletDescCreateTime := walletMixinFields1[0].Descriptor()
	// wallet.DefaultCreateTime holds the default value on creation for the create_time field.
	wallet.DefaultCreateTime = walletDescCreateTime.Default.(func() time.Time)
	// walletDescUpdateTime is the schema descriptor for update_time field.
	walletDescUpdateTime := walletMixinFields1[1].Descriptor()
	// wallet.DefaultUpdateTime holds the default value on creation for the update_time field.
	wallet.DefaultUpdateTime = walletDescUpdateTime.Default.(func() time.Time)
	// wallet.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	wallet.UpdateDefaultUpdateTime = walletDescUpdateTime.UpdateDefault.(func() time.Time)
	// walletDescVersion is the schema descriptor for version field.
	walletDescVersion := walletMixinFields2[0].Descriptor()
	// wallet.DefaultVersion holds the default value on creation for the version field.
	wallet.DefaultVersion = walletDescVersion.Default.(string)
	// walletDescLock is the schema descriptor for lock field.
	walletDescLock := walletFields[1].Descriptor()
	// wallet.DefaultLock holds the default value on creation for the lock field.
	wallet.DefaultLock = walletDescLock.Default.(bool)
	// walletDescBalance is the schema descriptor for balance field.
	walletDescBalance := walletFields[2].Descriptor()
	// wallet.DefaultBalance holds the default value on creation for the balance field.
	wallet.DefaultBalance = walletDescBalance.Default.(int)
	// wallet.BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	wallet.BalanceValidator = walletDescBalance.Validators[0].(func(int) error)
}

const (
	Version = "v0.4.3"                                          // Version of ent codegen.
	Sum     = "h1:ds9HENceKzpGBgCRlkZNq6TqBIegwKcF3e5reuV9Z0M=" // Sum of ent codegen.
)
