// Code generated by entc, DO NOT EDIT.

package wallet

import (
	"time"

	"github.com/facebook/ent"
)

const (
	// Label holds the string label denoting the wallet type in the database.
	Label = "wallet"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLock holds the string denoting the lock field in the database.
	FieldLock = "lock"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"

	// Table holds the table name of the wallet in the database.
	Table = "wallets"
)

// Columns holds all SQL columns for wallet fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldUpdateTime,
	FieldVersion,
	FieldUserID,
	FieldLock,
	FieldBalance,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/ftomza/go-qcbalu/wallet/repository/ent/runtime"
//
var (
	Hooks [1]ent.Hook
	// DefaultCreateTime holds the default value on creation for the create_time field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the update_time field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	UpdateDefaultUpdateTime func() time.Time
	// DefaultVersion holds the default value on creation for the version field.
	DefaultVersion string
	// DefaultLock holds the default value on creation for the lock field.
	DefaultLock bool
	// DefaultBalance holds the default value on creation for the balance field.
	DefaultBalance int
	// BalanceValidator is a validator for the "balance" field. It is called by the builders before save.
	BalanceValidator func(int) error
)
