// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import (
	mbs "github.com/ftomza/go-qcbalu/pkg/mbs"
	mock "github.com/stretchr/testify/mock"
)

// PUBService is an autogenerated mock type for the PUBService type
type PUBService struct {
	mock.Mock
}

// Publish provides a mock function with given fields: msg
func (_m *PUBService) Publish(msg *mbs.PUBMessage) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(*mbs.PUBMessage) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
