// Code generated by mockery v2.2.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RPCDelivery is an autogenerated mock type for the RPCDelivery type
type RPCDelivery struct {
	mock.Mock
}

// Data provides a mock function with given fields:
func (_m *RPCDelivery) Data() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// ParseData provides a mock function with given fields: out
func (_m *RPCDelivery) ParseData(out interface{}) error {
	ret := _m.Called(out)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
