// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebook/ent/dialect/sql"
)

// Wallet is the predicate function for wallet builders.
type Wallet func(*sql.Selector)
